#
# EAP Configuration for FreeRADIUS
#

eap {
    default_eap_type = tls
    timer_expire = 60
    ignore_unknown_eap_types = no
    cisco_accounting_username_bug = no
    max_sessions = 4096
    
    tls {
        tls_config = ${confdir}/tls-config
    }
    
    ttls {
        tls_config = ${confdir}/tls-config
        default_eap_type = mschapv2
        copy_request_to_tunnel = yes
        use_tunneled_reply = no
    }
    
    peap {
        tls_config = ${confdir}/tls-config
        default_eap_type = mschapv2
        copy_request_to_tunnel = yes
        use_tunneled_reply = no
        proxy_tunneled_request_as_eap = yes
    }
    
    mschapv2 {
        with_ntdomain_hack = no
        send_error_response = no
    }
}
